### ISSUE TITLE
Dependency missing from repositories?

### ISSUE THREAD

**Issue by mstuban** [trolley/java-sdk#2]
My project's Gradle build cannot find the following dependency (written in Maven for clarity):

```
<dependency>
    <groupId>ca.paymentrails</groupId>
    <artifactId>paymentrails</artifactId>
    <version>1.0</version>
</dependency>

```
I have the mavenCentral() repository declared. Is this lib stored on some other unknown repo, perhaps?
Also, the Readme.MD file contains nothing but the following under the dependency code snippet:

> The library is hosted at [insert github link]

**Comment by Aman-Aalam** [comment]
Solved by `v1.1.0`
